Bugfix/kaleb coberly/preparse ref to checkout (#9)

diff --git a/.github/workflows/QC.yml b/.github/workflows/QC.yml
--- a/.github/workflows/QC.yml
+++ b/.github/workflows/QC.yml
@@ -59,13 +59,23 @@ jobs:
     name: Run Linting, Security, Tests, and Dist Build
 
     steps:
-      - name: Debug Ref Info
+      - name: Validate and set REF_TO_CHECKOUT
+        id: validate-ref
+        env:
+          REF_TO_CHECKOUT: ${{ inputs.REF_TO_CHECKOUT }}
         run: |
-          echo "Checking out ref: ${{ inputs.REF_TO_CHECKOUT }}"
+          if [[ ! "$REF_TO_CHECKOUT" =~ ^refs/(heads|pull|tags)/[A-Za-z0-9._/-]+$ ]]; then
+            echo "Invalid ref: $REF_TO_CHECKOUT"
+            exit 1
+          fi
+
+          echo "Checking out ref: $REF_TO_CHECKOUT"
+          echo "$REF_TO_CHECKOUT=$REF_TO_CHECKOUT" >> $GITHUB_OUTPUT
+
       - name: Checkout repo
         uses: actions/checkout@v4
         with:
-          ref: ${{ inputs.REF_TO_CHECKOUT }}
+          ref: ${{ steps.validate-ref.outputs.REF_TO_CHECKOUT }}
           token: ${{ secrets.CHECKOUT_SHARED }}
 
       - name: Set up Node with Volta
